phosphosite:
  dataset:
    train: ../Darkin_Dataset/datasets/random_seed_12345/ZSL/train_data_random_seed_12345.csv
    validation: ../Darkin_Dataset/datasets/random_seed_12345/ZSL/ZSL_validation_data_random_seed_12345.csv
    test: ../Darkin_Dataset/datasets/random_seed_12345/ZSL/ZSL_test_data_random_seed_12345.csv
    processor:
      processor_type: esm
      model_name: esm2_t33_650M_UR50D
      read_embeddings: true
      phosphosite_embedding_path: /arf/scratch/esunar/darkin/bilinear_zero_shot_model/embeddings/ESM2SeqEmb.pt
  model:
    model_type: esm
    model_name: esm2_t33_650M_UR50D
    embedding_mode: avg
    freeze: true
    unfrozen_layers: ''
  
  sequence_model:
    model_type: bilstm
    hidden_size: 512
    use_sequence_model: false

kinase:
  dataset:
    train: ../Darkin_Dataset/data_files/kinase_properties.csv
    validation: ../Darkin_Dataset/data_files/kinase_properties.csv
    test: ../Darkin_Dataset/data_files/kinase_properties.csv
    processor:
      processor_type: esm
      model_name: esm2_t33_650M_UR50D
      read_embeddings: true
      kinase_embedding_path: /arf/scratch/esunar/darkin/bilinear_zero_shot_model/embeddings/ESM2KinaseEmb_withattentionmask.pt
      use_family: true
      use_group: true
      use_enzymes: true
      use_kin2vec: false
      use_pathway: false
      active_site:
        use_active_site: false
        from_context: false
        embedding_mode: cls
      use_domain: true
  model:
    model_type: esm
    model_name: esm2_t33_650M_UR50D
    embedding_mode: avg
    freeze: true
    unfrozen_layers: ''

training:
  train:
    batch_size: 16
  validation:
    batch_size: 1
  num_epochs: 60
  learning_rate: 0.001
  normalize_data: true
  save_model: true
  saved_model_path: checkpoints/esm2_avg
  kinase_encoder_save_path : checkpoints/encoders/esm2_avg_all/kinase_encoder.pkl
  set_seed: true
  precision: '32-true'
  normalize_phosphosite_data: true
  normalize_kinase_data: false
  train_batch_size: 16
  test_batch_size: 1

testing:
  kinase_encoder_load_path : checkpoints/encoders/esm2_avg_all/kinase_encoder.pkl
  load_model_path: checkpoints/esm2_avg
  checkpoint_file_name: 'XXX'

logging:
  use_wandb : false
  log_name : 'esm_deneme'
  project_name : 'Test_DKZ'
  entity_name : 'deepkinzero'
  wandb:
    use_wandb : false
    log_name : 'esm1b_w'
    project_name : 'transformer-training'
    entity_name : 'deepkinzero'
  local:
    run_test_suite: false
    use_config_filename: false
    save_predictions: false
    checkpoint_file_name: 'esm1b_w'
    saved_model_path: checkpoints/esm1b_models
    kinase_encoder_save_path : checkpoints/esm1b_models/ke_esm1b_w.pkl

hyper_parameters:
  gamma : 0.9756514890680584
  learning_rate : 0.00259774443912184
  optimizer : 'SGD'
  scheduler_type : 'CosineAnnealingLR'
  weight_decay: 0.00011754554440719858
  temperature: 1