phosphosite:
  dataset:
    train: ../Darkin_Dataset/datasets/random_seed_12345/ZSL/train_data_random_seed_12345.csv
    validation: ../Darkin_Dataset/datasets/random_seed_12345/ZSL/ZSL_validation_data_random_seed_12345.csv
    test: ../Darkin_Dataset/datasets/random_seed_12345/ZSL/ZSL_test_data_random_seed_12345.csv
    processor:
      processor_type: saprot
      model_name: SaProt
      read_embeddings: true
      phosphosite_embedding_path: /arf/scratch/esunar/darkin/bilinear_zero_shot_model/embeddings/SaProtSeqEmb.pt
  model:
    model_type: saprot
    model_name: SaProt
    embedding_mode: cls
    freeze: true
    unfrozen_layers: ''
  
  sequence_model:
    model_type: bilstm
    hidden_size: 512
    use_sequence_model: false

kinase:
  dataset:
    train: ../Darkin_Dataset/data_files/kinase_properties.csv
    validation: ../Darkin_Dataset/data_files/kinase_properties.csv
    test: ../Darkin_Dataset/data_files/kinase_properties.csv
    processor:
      processor_type: saprot
      model_name: SaProt
      read_embeddings: true
      kinase_embedding_path: /arf/scratch/esunar/darkin/bilinear_zero_shot_model/embeddings/SaProtKinaseEmb.pt
      use_family: true
      use_group: true
      use_enzymes: true
      use_kin2vec: false
      use_pathway: false
      active_site:
        use_active_site: false
        from_context: false
        embedding_mode: cls
      use_domain: true
  model:
    model_type: saprot
    model_name: SaProt
    embedding_mode: cls
    freeze: true
    unfrozen_layers: ''

training:
  train:
    batch_size: 16
  validation:
    batch_size: 1
  num_epochs: 60
  learning_rate: 0.001
  normalize_data: true
  save_model: true
  saved_model_path: checkpoints/saprot_cls_12345
  kinase_encoder_save_path : checkpoints/encoders/saprot_cls_all_12345/kinase_encoder.pkl
  set_seed: true
  precision: '32-true'
  normalize_phosphosite_data: true
  normalize_kinase_data: false
  train_batch_size: 16
  test_batch_size: 1

testing:
  kinase_encoder_load_path : checkpoints/encoders/saprot_cls_all_12345/kinase_encoder.pkl
  load_model_path: checkpoints/saprot_cls_12345
  checkpoint_file_name: 'XXX'

logging:
  use_wandb : false
  log_name : 'saprot_deneme'
  project_name : 'Test_DKZ'
  entity_name : 'deepkinzero'
  wandb:
    use_wandb : false
    log_name : 'esm1b_w'
    project_name : 'transformer-training'
    entity_name : 'deepkinzero'
  local:
    run_test_suite: false
    use_config_filename: false
    save_predictions: false
    checkpoint_file_name: 'esm1b_w'
    saved_model_path: checkpoints/esm1b_models
    kinase_encoder_save_path : checkpoints/esm1b_models/ke_esm1b_w.pkl

hyper_parameters:
  gamma : 0.9719558586758905
  learning_rate : 0.006425822638523415
  optimizer : 'SGD'
  scheduler_type : 'CosineAnnealingLR'
  weight_decay: 0.0019988253720321946
  temperature: 1

random_seed : 12345